// <auto-generated />
using System;
using BeautyCrm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeautyCrm.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BeautyDbContext))]
    [Migration("20261008092926_beauty_staff_hardening")]
    partial class beauty_staff_hardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.AiAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("proposed")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_ai_actions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_ai_actions_tenant_id_id");

                    b.HasIndex("TenantId", "AppointmentId")
                        .HasDatabaseName("ix_beauty_ai_actions_tenant_id_appointment_id");

                    b.HasIndex("TenantId", "ConversationId")
                        .HasDatabaseName("ix_beauty_ai_actions_tenant_id_conversation_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_beauty_ai_actions_tenant_id_created_at")
                        .HasFilter("status = 'proposed'");

                    b.ToTable("beauty_ai_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_ai_actions_status", "status IN ('proposed', 'confirmed', 'rejected', 'executed', 'failed')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTimeOffset>("EndsAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("IdempotencyKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key_hash");

                    b.Property<string>("IdempotencyRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_request_hash");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PriceFinal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_final");

                    b.Property<decimal>("PriceOriginal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_original");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<string>("PublicTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_token_hash");

                    b.Property<string>("ReminderOption")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("none")
                        .HasColumnName("reminder_option");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_appointments");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_appointments_tenant_id_id");

                    b.HasIndex("TenantId", "IdempotencyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_beauty_appointments_idempotency")
                        .HasFilter("idempotency_key_hash IS NOT NULL");

                    b.HasIndex("TenantId", "PromotionId")
                        .HasDatabaseName("ix_beauty_appointments_tenant_id_promotion_id");

                    b.HasIndex("TenantId", "PublicTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_beauty_appointments_public_token")
                        .HasFilter("public_token_hash IS NOT NULL");

                    b.HasIndex("TenantId", "ServiceId")
                        .HasDatabaseName("ix_beauty_appointments_tenant_id_service_id");

                    b.HasIndex("TenantId", "ClientId", "StartsAt")
                        .HasDatabaseName("ix_beauty_appointments_tenant_id_client_id_starts_at");

                    b.HasIndex("TenantId", "LocationId", "StartsAt")
                        .HasDatabaseName("ix_beauty_appointments_tenant_id_location_id_starts_at");

                    b.HasIndex("TenantId", "SpecialistId", "StartsAt")
                        .HasDatabaseName("ix_beauty_appointments_tenant_id_specialist_id_starts_at");

                    b.ToTable("beauty_appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_appointments_duration_positive", "duration_minutes > 0");

                            t.HasCheckConstraint("ck_beauty_appointments_payment_method", "payment_method IS NULL OR payment_method IN ('card', 'cash')");

                            t.HasCheckConstraint("ck_beauty_appointments_prices_non_negative", "price_original >= 0 AND price_final >= 0");

                            t.HasCheckConstraint("ck_beauty_appointments_reminder_option", "reminder_option IN ('none', '1h', '2h')");

                            t.HasCheckConstraint("ck_beauty_appointments_source", "source IN ('admin', 'online', 'telegram', 'instagram')");

                            t.HasCheckConstraint("ck_beauty_appointments_status", "status IN ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.CancellationSettingsRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("DeductFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deduct_fee");

                    b.Property<int>("FeePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fee_percent");

                    b.Property<int>("RefundPercentInWindow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("refund_percent_in_window");

                    b.Property<int>("RefundPercentOutside")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("refund_percent_outside");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WindowHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("window_hours");

                    b.HasKey("Id")
                        .HasName("pk_beauty_cancellation_settings");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_cancellation_settings_tenant_id_id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_beauty_cancellation_settings_tenant_id");

                    b.ToTable("beauty_cancellation_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_cancellation_settings_percents", "refund_percent_in_window BETWEEN 0 AND 100 AND refund_percent_outside BETWEEN 0 AND 100 AND fee_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_beauty_cancellation_settings_window", "window_hours >= 0 AND window_hours <= 720");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CredentialsEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("credentials_encrypted");

                    b.Property<string>("CredentialsLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("credentials_last4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_channels");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_channels_tenant_id_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_beauty_channels_tenant_id_location_id");

                    b.ToTable("beauty_channels", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_channels_type", "type IN ('telegram', 'instagram', 'facebook', 'whatsapp', 'viber', 'widget')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("MarketingConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("marketing_consent");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("Unsubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("unsubscribed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_clients");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_clients_tenant_id_id");

                    b.HasIndex("TenantId", "Phone")
                        .HasDatabaseName("ix_beauty_clients_tenant_id_phone")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("beauty_clients", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.ClientNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_client_notes");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_client_notes_tenant_id_id");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_beauty_client_notes_tenant_id_client_id");

                    b.ToTable("beauty_client_notes", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalChatId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_chat_id");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_conversations");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_conversations_tenant_id_id");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("ix_beauty_conversations_tenant_id_client_id");

                    b.HasIndex("TenantId", "LastMessageAt")
                        .HasDatabaseName("ix_beauty_conversations_tenant_id_last_message_at")
                        .HasFilter("status = 'open'");

                    b.HasIndex("TenantId", "ChannelId", "ExternalChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_beauty_conversations_tenant_id_channel_id_external_chat_id");

                    b.ToTable("beauty_conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_conversations_status", "status IN ('open', 'closed')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid?>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_invites_tenant_id_id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_invites_tenant_id_email");

                    b.HasIndex("TenantId", "InvitedByUserId")
                        .HasDatabaseName("ix_invites_tenant_id_invited_by_user_id");

                    b.HasIndex("TenantId", "SpecialistId")
                        .HasDatabaseName("ix_invites_tenant_id_specialist_id");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_tenant_id_token_hash");

                    b.ToTable("invites", null, t =>
                        {
                            t.HasCheckConstraint("ck_invites_role", "role IN ('admin', 'specialist')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_locations");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_locations_tenant_id_id");

                    b.ToTable("beauty_locations", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_message_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sender_type");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("received")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_messages");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_messages_tenant_id_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_beauty_messages_tenant_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("TenantId", "ConversationId", "SentAt")
                        .HasDatabaseName("ix_beauty_messages_tenant_id_conversation_id_sent_at");

                    b.ToTable("beauty_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_messages_direction", "direction IN ('inbound', 'outbound')");

                            t.HasCheckConstraint("ck_beauty_messages_sender_type", "sender_type IN ('client', 'staff', 'ai', 'system')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_payments");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_payments_tenant_id_id");

                    b.HasIndex("TenantId", "AppointmentId")
                        .HasDatabaseName("ix_beauty_payments_tenant_id_appointment_id");

                    b.HasIndex("TenantId", "Provider", "ProviderPaymentId")
                        .HasDatabaseName("ix_beauty_payments_tenant_id_provider_provider_payment_id")
                        .HasFilter("provider_payment_id IS NOT NULL");

                    b.ToTable("beauty_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_payments_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_beauty_payments_method", "method IN ('card', 'cash')");

                            t.HasCheckConstraint("ck_beauty_payments_status", "status IN ('pending', 'paid', 'failed', 'refunded')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_promotions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_promotions_tenant_id_id");

                    b.ToTable("beauty_promotions", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_promotions_discount_type", "discount_type IN ('percent', 'fixed')");

                            t.HasCheckConstraint("ck_beauty_promotions_discount_value", "discount_value > 0 AND (discount_type <> 'percent' OR discount_value <= 100)");

                            t.HasCheckConstraint("ck_beauty_promotions_period", "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.PromotionLocation", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PromotionId", "LocationId")
                        .HasName("pk_beauty_promotion_locations");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_beauty_promotion_locations_tenant_id_location_id");

                    b.HasIndex("TenantId", "PromotionId")
                        .HasDatabaseName("ix_beauty_promotion_locations_tenant_id_promotion_id");

                    b.ToTable("beauty_promotion_locations", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.PromotionService", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PromotionId", "ServiceId")
                        .HasName("pk_beauty_promotion_services");

                    b.HasIndex("TenantId", "PromotionId")
                        .HasDatabaseName("ix_beauty_promotion_services_tenant_id_promotion_id");

                    b.HasIndex("TenantId", "ServiceId")
                        .HasDatabaseName("ix_beauty_promotion_services_tenant_id_service_id");

                    b.ToTable("beauty_promotion_services", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_refresh_tokens_tenant_id_id");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_tenant_id_token_hash");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_refresh_tokens_tenant_id_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("scheduled")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_reminders");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_reminders_tenant_id_id");

                    b.HasIndex("TenantId", "AppointmentId")
                        .HasDatabaseName("ix_beauty_reminders_tenant_id_appointment_id");

                    b.HasIndex("TenantId", "ScheduledAt")
                        .HasDatabaseName("ix_beauty_reminders_tenant_id_scheduled_at")
                        .HasFilter("status = 'scheduled'");

                    b.ToTable("beauty_reminders", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_reminders_status", "status IN ('scheduled', 'sent', 'failed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_services");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_services_tenant_id_id");

                    b.ToTable("beauty_services", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_services_duration_positive", "duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.ServicePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_service_prices");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_service_prices_tenant_id_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_beauty_service_prices_tenant_id_location_id");

                    b.HasIndex("TenantId", "ServiceId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_beauty_service_prices_tenant_id_service_id_location_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "ServiceId", "LocationId"), false);

                    b.ToTable("beauty_service_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_service_prices_price_non_negative", "price >= 0");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_beauty_specialists");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_specialists_tenant_id_id");

                    b.ToTable("beauty_specialists", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_beauty_specialist_absences");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_specialist_absences_tenant_id_id");

                    b.HasIndex("TenantId", "CancelledByUserId")
                        .HasDatabaseName("ix_beauty_specialist_absences_tenant_id_cancelled_by_user_id");

                    b.HasIndex("TenantId", "DecidedByUserId")
                        .HasDatabaseName("ix_beauty_specialist_absences_tenant_id_decided_by_user_id");

                    b.HasIndex("TenantId", "RequestedByUserId")
                        .HasDatabaseName("ix_beauty_specialist_absences_tenant_id_requested_by_user_id");

                    b.HasIndex("TenantId", "SpecialistId", "DateFrom")
                        .HasDatabaseName("ix_beauty_specialist_absences_tenant_id_specialist_id_date_from");

                    b.ToTable("beauty_specialist_absences", null, t =>
                        {
                            t.HasCheckConstraint("ck_beauty_specialist_absences_dates", "date_to >= date_from");

                            t.HasCheckConstraint("ck_beauty_specialist_absences_note", "note IS NULL OR char_length(note) <= 500");

                            t.HasCheckConstraint("ck_beauty_specialist_absences_status", "status IN ('requested', 'approved', 'rejected', 'cancelled')");

                            t.HasCheckConstraint("ck_beauty_specialist_absences_type", "type IN ('sick', 'vacation', 'day_off', 'other')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("working_hours");

                    b.HasKey("Id")
                        .HasName("pk_beauty_specialist_locations");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_beauty_specialist_locations_tenant_id_id");

                    b.HasIndex("TenantId", "LocationId")
                        .HasDatabaseName("ix_beauty_specialist_locations_tenant_id_location_id");

                    b.HasIndex("TenantId", "SpecialistId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_beauty_specialist_locations_tenant_id_specialist_id_locatio");

                    b.ToTable("beauty_specialist_locations", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistServiceLink", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.HasKey("TenantId", "SpecialistId", "ServiceId")
                        .HasName("pk_beauty_specialist_services");

                    b.HasIndex("TenantId", "ServiceId")
                        .HasDatabaseName("ix_beauty_specialist_services_tenant_id_service_id");

                    b.ToTable("beauty_specialist_services", (string)null);
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string[]>("Modules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("modules")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_slug", "slug ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'");

                            t.HasCheckConstraint("ck_tenants_status", "status IN ('active', 'suspended')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid?>("SpecialistId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialist_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_users_tenant_id_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.HasIndex("TenantId", "SpecialistId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_specialist_id")
                        .HasFilter("specialist_id IS NOT NULL");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('owner', 'admin', 'specialist')");
                        });
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.AiAction", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppointmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_ai_actions_beauty_appointments_tenant_id_appointment");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("TenantId", "ConversationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_ai_actions_beauty_conversations_tenant_id_conversati");

                    b.Navigation("Appointment");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Appointment", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("TenantId", "ClientId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_appointments_beauty_clients_tenant_id_client_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("TenantId", "LocationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_appointments_beauty_locations_tenant_id_location_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_appointments_beauty_promotions_tenant_id_promotion_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_appointments_beauty_services_tenant_id_service_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_appointments_beauty_specialists_tenant_id_specialist");

                    b.Navigation("Client");

                    b.Navigation("Location");

                    b.Navigation("Promotion");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Channel", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("TenantId", "LocationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_channels_beauty_locations_tenant_id_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.ClientNote", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("TenantId", "ClientId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_client_notes_beauty_clients_tenant_id_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Conversation", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("TenantId", "ChannelId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_conversations_beauty_channels_tenant_id_channel_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("TenantId", "ClientId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_conversations_beauty_clients_tenant_id_client_id");

                    b.Navigation("Channel");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Invite", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_tenants_tenant_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("TenantId", "InvitedByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invites_users_tenant_id_invited_by_user_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invites_beauty_specialists_tenant_id_specialist_id");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Message", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("TenantId", "ConversationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_messages_beauty_conversations_tenant_id_conversation");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Payment", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppointmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_payments_beauty_appointments_tenant_id_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.PromotionLocation", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("TenantId", "LocationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_promotion_locations_beauty_locations_tenant_id_locat");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_promotion_locations_beauty_promotions_tenant_id_prom");

                    b.Navigation("Location");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.PromotionService", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("TenantId", "PromotionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_promotion_services_beauty_promotions_tenant_id_promo");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_promotion_services_beauty_services_tenant_id_service");

                    b.Navigation("Promotion");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_tenants_tenant_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_tenant_id_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.Reminder", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppointmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_reminders_beauty_appointments_tenant_id_appointment_");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.ServicePrice", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("TenantId", "LocationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_beauty_service_prices_beauty_locations_tenant_id_location_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_service_prices_beauty_services_tenant_id_service_id");

                    b.Navigation("Location");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistAbsence", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CancelledByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_specialist_absences_users_tenant_id_cancelled_by_use");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DecidedByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_beauty_specialist_absences_users_tenant_id_decided_by_user_");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RequestedByUserId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_absences_users_tenant_id_requested_by_use");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_absences_beauty_specialists_tenant_id_spe");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistLocation", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("TenantId", "LocationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_locations_beauty_locations_tenant_id_loca");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_locations_beauty_specialists_tenant_id_sp");

                    b.Navigation("Location");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.SpecialistServiceLink", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_services_beauty_services_tenant_id_servic");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_beauty_specialist_services_beauty_specialists_tenant_id_spe");

                    b.Navigation("Service");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("BeautyCrm.Infrastructure.Data.Entities.User", b =>
                {
                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.HasOne("BeautyCrm.Infrastructure.Data.Entities.Specialist", "Specialist")
                        .WithMany()
                        .HasForeignKey("TenantId", "SpecialistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_beauty_specialists_tenant_id_specialist_id");

                    b.Navigation("Specialist");
                });
#pragma warning restore 612, 618
        }
    }
}
